# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='nome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
