version: '2'
services:
  web:
    #build: .
    #image: culturagovbr/salic-br:1.3
    #container_name: salic-br
    ports:
     - "80:80"
    volumes:
     - ./app:/var/www/salic-br
    environment:
     - DB_HOST=192.168.15.11
     restart: always
